name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build the project
        run: npm run build
      - name: Test the project
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run e2e:test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notify on success
        if: ${{ success() && github.event_name == 'push' }}
        uses: Ilshidur/action-discord@0v0.3.2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Deploy succeeded! Deployed to https://full-stack-open-pokedex-j79i.onrender.com/version by Ayman"
          username: CustomUsername
          avatar-url: 'https://path/to/avatar.png' # optional

      - name: Notify on failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@0v0.3.2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Something went wrong! Commit link: https://github.com/${{ github.repository }}/commit/${{ github.sha }} broke the build."
          username: CustomUsername


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
